import os
import logging
from typing import Any
from pathlib import Path

from weasyprint import HTML, CSS # noqa
from weasyprint.text.fonts import FontConfiguration

from core.config import settings
from constants.pdf import PDF_CSS
from utils.helpers import sanitize_filename

logger = logging.getLogger(__name__)


class PDFService:
    """Service for handling PDF generation from HTML content."""

    def __init__(self):
        self.output_dir = Path(settings.UPLOAD_DIR) / "pdfs"
        self.output_dir.mkdir(exist_ok=True, parents=True)

        self.font_config = FontConfiguration()

    def generate_pdf(
        self, html_content: str, video_info: dict[str, Any]
    ) -> str:
        """
        Generate PDF from HTML content.
        """
        try:
            title = sanitize_filename(video_info.get("title", "video_notes"))
            video_id = video_info.get("id", "unknown")
            output_filename = f"{title}_{video_id}_notes.pdf"

            output_path = self.output_dir / output_filename

            styled_html = self._add_professional_styling(html_content)

            # with open("styled_html.html", "w") as f:
            #     f.write(styled_html)

            html_doc = HTML(string=styled_html)

            html_doc.write_pdf(
                str(output_path),
                font_config=self.font_config,
                presentational_hints=True,
            )

            logger.info(f"Successfully generated PDF: {output_path}")
            return str(output_path)

        except Exception as ex:
            logger.exception(f"Error generating PDF: {str(ex)}")
            raise ValueError(f"Failed to generate PDF: {str(ex)}")

    def _add_professional_styling(self, html_content: str) -> str:
        """
        Add comprehensive professional styling to HTML content.
        """

        full_html = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>YouTube Video Analysis</title>
            {PDF_CSS}
        </head>
        <body>
            {html_content}
            <div class="footer-note">
                Generated by YT-PDF Service - Transform YouTube content into actionable insights
            </div>
        </body>
        </html>
        """

        return full_html

    def cleanup_pdf(self, pdf_path: str) -> None:
        """
        Clean up generated PDF file.
        """
        try:
            if os.path.exists(pdf_path):
                os.unlink(pdf_path)
                logger.info(f"Cleaned up PDF: {pdf_path}")
        except Exception as ex:
            logger.warning(f"Failed to cleanup PDF {pdf_path}: {str(ex)}")

    def get_pdf_info(self, pdf_path: str) -> dict[str, Any]:
        """
        Get information about generated PDF.
        """
        try:
            if not os.path.exists(pdf_path):
                raise FileNotFoundError("PDF file not found")

            file_stats = os.stat(pdf_path)

            return {
                "file_size": file_stats.st_size,
                "file_size_mb": round(file_stats.st_size / (1024 * 1024), 2),
                "created_at": file_stats.st_ctime,
                "filename": os.path.basename(pdf_path),
            }

        except Exception as ex:
            logger.exception(f"Error getting PDF info: {str(ex)}")
            return {}


pdf_service = PDFService()